spring:
  datasource:
    url: jdbc:h2:mem:orders
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8081

logging:
  level:
    com.acme: DEBUG
